In [15]:
#난수 정수 100개 생성-> 내림차순 정렬->상위 5개 table1로 저장, 나머지는 table2로 분리 후 각각 출력
import numpy as np
x=np.random.randint(0,101,size=100)
x=np.sort(x)[::-1]
print(x)
table1=x[0:5]
print(table1)
table2=x[5:]
print(table2)

[100  99  96  95  93  93  92  91  91  90  90  89  89  89  88  88  85  84
  84  83  83  82  81  79  79  78  77  75  75  75  73  73  73  72  71  71
  70  67  65  65  64  64  60  59  59  58  57  56  53  53  52  52  52  51
  51  50  49  49  48  47  47  46  45  42  42  42  42  41  41  37  37  36
  34  34  33  32  29  28  25  24  24  23  23  20  16  16  14  14  10  10
   9   8   7   6   5   5   5   4   3   2]
[100  99  96  95  93]
[93 92 91 91 90 90 89 89 89 88 88 85 84 84 83 83 82 81 79 79 78 77 75 75
 75 73 73 73 72 71 71 70 67 65 65 64 64 60 59 59 58 57 56 53 53 52 52 52
 51 51 50 49 49 48 47 47 46 45 42 42 42 42 41 41 37 37 36 34 34 33 32 29
 28 25 24 24 23 23 20 16 16 14 14 10 10  9  8  7  6  5  5  5  4  3  2]


In [3]:
import pandas as pd
data=pd.Series([0.2,0.5,0.51],
index=['a','b','d'])

In [4]:
data

a    0.20
b    0.50
d    0.51
dtype: float64

In [5]:
'a' in data

True

In [6]:
data.keys()

Index(['a', 'b', 'd'], dtype='object')

In [7]:
data.values()

TypeError: 'numpy.ndarray' object is not callable

In [8]:
list(data.items())

[('a', 0.2), ('b', 0.5), ('d', 0.51)]

In [9]:
data['d']

0.51

In [10]:
data[2]

C:\Users\user\AppData\Local\Temp\ipykernel_2612\1082122490.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  data[2]


0.51

In [11]:
data[0:1]

a    0.2
dtype: float64

In [12]:
data['a':'b']

a    0.2
b    0.5
dtype: float64

In [13]:
area = pd.Series({'California': 423967, 'Texas': 695662,
                  'New York': 141297, 'Florida': 170312,
                  'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
                 'New York': 19651127, 'Florida': 19552860,
                 'Illinois': 12882135})
data = pd.DataFrame({'area':area, 'pop':pop})
data

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [14]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [15]:
data['area']['Texas']

695662

In [16]:
data.keys()

Index(['area', 'pop'], dtype='object')

In [17]:
data['area'].keys()

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [18]:
data.area #data['area']로 적어야 함수와 에러가 나지 않는다

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [19]:
data.area.keys()

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [20]:
data.pop #pop메서드와 충돌이 일어날 수 있다.

<bound method DataFrame.pop of               area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135>

In [21]:
data['density']=data['pop']/data['area']

In [22]:
data['density']

California     90.413926
Texas          38.018740
New York      139.076746
Florida       114.806121
Illinois       85.883763
Name: density, dtype: float64

In [23]:
data

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [24]:
data.keys()

Index(['area', 'pop', 'density'], dtype='object')

In [25]:
data.T

California         Texas      New York       Florida      Illinois
area     4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
pop      3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
density  9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

In [26]:
data.values

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

In [28]:
data.values[0]

array([4.23967000e+05, 3.83325210e+07, 9.04139261e+01])

In [29]:
data.T

California         Texas      New York       Florida      Illinois
area     4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
pop      3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
density  9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

In [30]:
data.area[1]

C:\Users\user\AppData\Local\Temp\ipykernel_2612\2065652488.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  data.area[1]


695662

In [31]:
data['area'][2]

C:\Users\user\AppData\Local\Temp\ipykernel_2612\4248108338.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  data['area'][2]


141297

In [32]:
data['area']['Florida']

170312

In [35]:
data.loc[:'pop',:'Florida']

KeyError: 'Florida'

In [36]:
data.T

California         Texas      New York       Florida      Illinois
area     4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
pop      3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
density  9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

In [37]:
data.loc[:'Florida',:'pop']

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860

In [46]:
data[['area','pop']]

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [55]:
data.loc[:'pop',:'texas']

KeyError: 'texas'

In [56]:
area = pd.Series({'Alaska': 1723337, 'Texas': 695662,
                  'California': 423967}, name='area')
population = pd.Series({'California': 38332521, 'Texas': 26448193,
                        'New York': 19651127}, name='population')

In [57]:
population/area

Alaska              NaN
California    90.413926
New York            NaN
Texas         38.018740
dtype: float64

In [59]:
area.index

Index(['Alaska', 'Texas', 'California'], dtype='object')